//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Budget.SERVICE {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BusinessExceptionLibrary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinessExceptionLibrary() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Budget.SERVICE.BusinessExceptionLibrary", typeof(BusinessExceptionLibrary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce compte est utilisé par un autre utilisateur.
        /// </summary>
        internal static string BUS_ACC_ERR_000 {
            get {
                return ResourceManager.GetString("BUS_ACC_ERR_000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce numéro de compte existe déjà.
        /// </summary>
        internal static string BUS_ACC_ERR_001 {
            get {
                return ResourceManager.GetString("BUS_ACC_ERR_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant obligatoire.
        /// </summary>
        internal static string BUS_AS_ERR_001 {
            get {
                return ResourceManager.GetString("BUS_AS_ERR_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date intégration obligatoire.
        /// </summary>
        internal static string BUS_AS_ERR_002 {
            get {
                return ResourceManager.GetString("BUS_AS_ERR_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Libellé opération obligatoire.
        /// </summary>
        internal static string BUS_AS_ERR_003 {
            get {
                return ResourceManager.GetString("BUS_AS_ERR_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Opération obligatoire.
        /// </summary>
        internal static string BUS_AS_ERR_004 {
            get {
                return ResourceManager.GetString("BUS_AS_ERR_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Méthode opération obligatoire.
        /// </summary>
        internal static string BUS_AS_ERR_005 {
            get {
                return ResourceManager.GetString("BUS_AS_ERR_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type opération obligatoire.
        /// </summary>
        internal static string BUS_AS_ERR_006 {
            get {
                return ResourceManager.GetString("BUS_AS_ERR_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Catégorie opération obligatoire.
        /// </summary>
        internal static string BUS_AS_ERR_007 {
            get {
                return ResourceManager.GetString("BUS_AS_ERR_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import utilisé dans un ou plusieurs relevé de comptes.
        /// </summary>
        internal static string BUS_ASI_ERR_000 {
            get {
                return ResourceManager.GetString("BUS_ASI_ERR_000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un utilisateur possède déjà cette adresse Email .
        /// </summary>
        internal static string BUS_AUTH_ERR_000 {
            get {
                return ResourceManager.GetString("BUS_AUTH_ERR_000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le mot de passe doit être supérieur à 8 caractères.
        /// </summary>
        internal static string BUS_AUTH_ERR_001 {
            get {
                return ResourceManager.GetString("BUS_AUTH_ERR_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom utilisateur incorrect.
        /// </summary>
        internal static string BUS_AUTH_ERR_002 {
            get {
                return ResourceManager.GetString("BUS_AUTH_ERR_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le mail indiqué n&apos;existe pas.
        /// </summary>
        internal static string BUS_AUTH_ERR_003 {
            get {
                return ResourceManager.GetString("BUS_AUTH_ERR_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;utilisateur n&apos;existe pas.
        /// </summary>
        internal static string BUS_AUTH_ERR_004 {
            get {
                return ResourceManager.GetString("BUS_AUTH_ERR_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;adresse mail indiqué ne correspond pas à l&apos;adresse mail du compte.
        /// </summary>
        internal static string BUS_AUTH_ERR_005 {
            get {
                return ResourceManager.GetString("BUS_AUTH_ERR_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email non vérifié, connexion impossible.
        /// </summary>
        internal static string BUS_AUTH_ERR_006 {
            get {
                return ResourceManager.GetString("BUS_AUTH_ERR_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un utilisateur possède déjà ce pseudonyme.
        /// </summary>
        internal static string BUS_AUTH_ERR_007 {
            get {
                return ResourceManager.GetString("BUS_AUTH_ERR_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe incorrect.
        /// </summary>
        internal static string BUS_AUTH_ERR_008 {
            get {
                return ResourceManager.GetString("BUS_AUTH_ERR_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détail opération obligatoire.
        /// </summary>
        internal static string BUS_OD_ERR_001 {
            get {
                return ResourceManager.GetString("BUS_OD_ERR_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Opération obligatoire.
        /// </summary>
        internal static string BUS_OD_ERR_002 {
            get {
                return ResourceManager.GetString("BUS_OD_ERR_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot clef opération obligatoire.
        /// </summary>
        internal static string BUS_OD_ERR_003 {
            get {
                return ResourceManager.GetString("BUS_OD_ERR_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lieu opération obligatoire.
        /// </summary>
        internal static string BUS_OD_ERR_004 {
            get {
                return ResourceManager.GetString("BUS_OD_ERR_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot clef lieu obligatoire.
        /// </summary>
        internal static string BUS_OD_ERR_005 {
            get {
                return ResourceManager.GetString("BUS_OD_ERR_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Libellé recherche opération obligatoire.
        /// </summary>
        internal static string BUS_OD_ERR_006 {
            get {
                return ResourceManager.GetString("BUS_OD_ERR_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Libellé recherche lieu obligatoire.
        /// </summary>
        internal static string BUS_OD_ERR_007 {
            get {
                return ResourceManager.GetString("BUS_OD_ERR_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Opération obligatoire, suppression impossible.
        /// </summary>
        internal static string BUS_OPE_ERR_000 {
            get {
                return ResourceManager.GetString("BUS_OPE_ERR_000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Opération utilisée dans un ou plusieurs imports.
        /// </summary>
        internal static string BUS_OPE_ERR_001 {
            get {
                return ResourceManager.GetString("BUS_OPE_ERR_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Opération utilisée dans un ou plusieurs relevés de compte.
        /// </summary>
        internal static string BUS_OPE_ERR_002 {
            get {
                return ResourceManager.GetString("BUS_OPE_ERR_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Catégorie opération obligatoire, suppression impossible.
        /// </summary>
        internal static string BUS_OTF_ERR_000 {
            get {
                return ResourceManager.GetString("BUS_OTF_ERR_000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Catégorie opération utilisée dans un ou plusieurs import(s).
        /// </summary>
        internal static string BUS_OTF_ERR_001 {
            get {
                return ResourceManager.GetString("BUS_OTF_ERR_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Catégorie opération utilisée dans un ou plusieurs relevé(s) de compte.
        /// </summary>
        internal static string BUS_OTF_ERR_002 {
            get {
                return ResourceManager.GetString("BUS_OTF_ERR_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Catégorie opération utilisée dans une ou plusieurs type d&apos;opération(s).
        /// </summary>
        internal static string BUS_OTF_ERR_003 {
            get {
                return ResourceManager.GetString("BUS_OTF_ERR_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Catégorie opération utilisée dans une ou plusieurs customisation utilisateur.
        /// </summary>
        internal static string BUS_OTF_ERR_004 {
            get {
                return ResourceManager.GetString("BUS_OTF_ERR_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type opération obligatoire, suppression impossible.
        /// </summary>
        internal static string BUS_OTY_ERR_000 {
            get {
                return ResourceManager.GetString("BUS_OTY_ERR_000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type opération utilisée dans un ou plusieurs import(s).
        /// </summary>
        internal static string BUS_OTY_ERR_001 {
            get {
                return ResourceManager.GetString("BUS_OTY_ERR_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type opération utilisée dans un ou plusieurs relevé(s) de compte.
        /// </summary>
        internal static string BUS_OTY_ERR_002 {
            get {
                return ResourceManager.GetString("BUS_OTY_ERR_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type opération utilisée dans une ou plusieurs opération(s).
        /// </summary>
        internal static string BUS_OTY_ERR_003 {
            get {
                return ResourceManager.GetString("BUS_OTY_ERR_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Opération obligatoire.
        /// </summary>
        internal static string BUS_REF_OPE_ERR_001 {
            get {
                return ResourceManager.GetString("BUS_REF_OPE_ERR_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Libellé opération obligatoire.
        /// </summary>
        internal static string BUS_REF_OPE_ERR_002 {
            get {
                return ResourceManager.GetString("BUS_REF_OPE_ERR_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Opération déjà existante, ajout impossible.
        /// </summary>
        internal static string BUS_REF_OPE_ERR_003 {
            get {
                return ResourceManager.GetString("BUS_REF_OPE_ERR_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compte non trouvé, validation impossible.
        /// </summary>
        internal static string BUS_USER_ERR_000 {
            get {
                return ResourceManager.GetString("BUS_USER_ERR_000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Expiration du délai de validation du compte, validation impossible.
        /// </summary>
        internal static string BUS_USER_ERR_001 {
            get {
                return ResourceManager.GetString("BUS_USER_ERR_001", resourceCulture);
            }
        }
    }
}
